[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps/Garden.Garden
EditorStartupMap=/Game/Maps/Garden.Garden
GlobalDefaultGameMode=/Game/Gameplay/FlowGame_GM.FlowGame_GM_C

[/Script/Engine.Engine]
WorldSettingsClassName=/Script/Flow.FlowWorldSettings
GameViewportClientClassName=/Script/CommonUI.CommonGameViewportClient
bCanBlueprintsTickByDefault=False

[/Script/Engine.RendererSettings]
r.AllowStaticLighting=False
r.ReflectionMethod=2
r.GenerateMeshDistanceFields=False
r.DynamicGlobalIlluminationMethod=2
r.Lumen.TraceMeshSDFs=0
r.Shadow.Virtual.Enable=1
r.Mobile.EnableNoPrecomputedLightingCSMShader=1
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=true
r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8
r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8
r.Nanite=False
r.Nanite.ProjectEnabled=False

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.LocalPlayer]
AspectRatioAxisConstraint=AspectRatio_MaintainYFOV

[SystemSettings]
net.SubObjects.DefaultUseSubObjectReplicationList=1

[/Script/IrisCore.ObjectReplicationBridgeConfig]
DefaultSpatialFilterName=Spatial
!FilterConfigs=ClearArray
+FilterConfigs=(ClassName=/Script/Engine.LevelScriptActor, DynamicFilterName=NotRouted) ; Not needed
+FilterConfigs=(ClassName=/Script/Engine.Actor, DynamicFilterName=None)
+FilterConfigs=(ClassName=/Script/Engine.Info, DynamicFilterName=None)
+FilterConfigs=(ClassName=/Script/Engine.PlayerState, DynamicFilterName=None)
+FilterConfigs=(ClassName=/Script/Engine.Pawn, DynamicFilterName=Spatial)
+FilterConfigs=(ClassName=/Script/EntityActor.SimObject, DynamicFilterName=None)

[/Script/OnlineSubsystemUtils.IpNetDriver]
MaxClientRate=200000
MaxInternetClientRate=200000

[/Script/Engine.Engine]
+NetDriverDefinitions=(DefName="BeaconNetDriver",DriverClassName="/Script/OnlineSubsystemUtils.IpNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")

[OnlineServices]
DefaultServices=Null

[/Script/OnlineSubsystemUtils.PartyBeaconHost]
bIsValidationStrRequired = false

[ConsoleVariables]
net.MaxRPCPerNetUpdate=10
net.PingExcludeFrameTime=1
net.AllowAsyncLoading=1
net.DelayUnmappedRPCs=1
net.AllowPIESeamlessTravel=1
a.EnableQueuedAnimEventsOnServer=1

[/Script/Engine.EditorStreamingSettings]
s.ZenLoaderEnabled=True

[/Script/Engine.CollisionProfile]
+Profiles=(Name="Projectile",CollisionEnabled=QueryOnly,ObjectTypeName="Projectile",CustomResponses=,HelpMessage="Preset for projectiles",bCanModify=True)
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel1,Name="Projectile",DefaultResponse=ECR_Block,bTraceType=False,bStaticObject=False)
+EditProfiles=(Name="Trigger",CustomResponses=((Channel=Projectile, Response=ECR_Ignore)))

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=31557ECC48E9AFF65003F395925C0D21
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

[CoreRedirects]
; https://docs.unrealengine.com/5.5/en-US/core-redirects-in-unreal-engine/

